name: Using Variables
on:
    push:
    worlflow_dispatch:
env:
    WORKFLOW_VAR: 'I am a workflow env var'
    OVERWRITTEN: 'I will be overwrittten'
jobs:
    echo:
        runs-on: ubuntu-latest 
        env:
            STEP_VAR: 'I am a step env var'
            step_var2: 'I am another step var'
        steps:
            - name: Print Env Variables

              run: |
                echo "Step env var: ${{ env.STEP_VAR }}"  
                echo "Step env var 2: ${{ env.step_var2 }}"
                echo "Job env var: ${{ env.WORKFLOW_VAR }}"
                echo "Overwritten: ${{ env.OVERWRITTEN }}"
            - name: Overwrite Job Variable
              env:
                OVERWRITTEN: "I've been overwritten at step level"
              run: |
                echo: "Step env var: ${{ env.OVERWRITTEN }}"
