name: 09 -  Using functions
on:
    pull_request:
    workflow_dispatch:
jobs:
    echo1:
        runs-on: ubuntu-latest
        steps:
            - name: Print PR Title 
              run: echo "${{ github.event.pull_request.title }}"
            - name: Print PR labels
              run: |
                cat << EOF
                ${{ toJSON(github.event.pull_request.labels) }}
                EOF
            - name: Bug Step
              if: ${{ !cancelled() && contains(github.event.pull_request.title, 'fix' )}}
              run: echo "I am a bug fix for Sure"
            - name: Failing step
              run: exit 1
            - name: I will be skipped
              if: ${{ success() }}
              run: echo "I will print if previous steps succeed"
            - name: I will execute
              if: ${{ failure() }}
              run: echo "I will print if any previous step fails"
            - name: I will execute if not cancelled
              if: ${{ !cancelled() }}
              run: echo "I will always print, except the workflow is cancelled"
            - name: I wil be executed if cancelled
              if: ${{ cancelled() }}
              run: echo "I will be executed if the workflow is cancelled"

